# fly.toml app configuration file generated for full-stack-open-part11-phoneapp on 2024-08-28T11:49:07-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-part11-phoneapp'
primary_region = 'mia'

[build]

[processes]
app = "node index.js"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
